import streamlit as st  
import pandas as pd    
from reportlab.platypus import SimpleDocTemplate, Paragraph
from reportlab.lib.styles import getSampleStyleSheet
from pathlib import Path 
import os  
from reportlab.lib.enums import TA_CENTER
from reportlab.lib.colors import navy
from datetime import datetime
from reportlab.platypus import Spacer, PageBreak
from reportlab.lib.styles import ParagraphStyle
from reportlab.lib.enums import TA_CENTER
from reportlab.lib.colors import navy
from reportlab.platypus import Table, TableStyle
from reportlab.lib import colors
from datetime import datetime
from auth_guard import check_login
from components.sidebar import show_sidebar


# Initialize session state variables
defaults = {
    "dataset_path": None,
    "current_price": 0.0,
    "expected_return": 0.0,
    "confidence": 0.0,
    "recommendation": "",
    "future_predictions": None,
}

for key, default in defaults.items():
    if key not in st.session_state:
        st.session_state[key] = default

from auth_guard import check_login
from components.sidebar import show_sidebar

show_sidebar()
check_login()

# Read    
csv_path = st.session_state["dataset_path"]
df = pd.read_csv(csv_path)
 
# Report Generate
def generate_report() :
    # Cover Page
    story = []
    styles = getSampleStyleSheet()
    title = ParagraphStyle("TitleStyle", 
                           parent = styles["Title"],
                           alignment = TA_CENTER,
                           fontSize = 26,
                           textColor = navy,
                           spaceAfter = 20)
    story.append(Paragraph("A-PQRP", title))
    story.append(Paragraph("AI Powered Quant Research Platform", styles["Heading1"]))
    story.append(Paragraph("Financial Analysis Report", styles["Heading2"]))
    story.append(Spacer(1,30))
    story.append(Paragraph(f"Generated on : {datetime.now().strftime('%d %B %Y %H : %M')}", styles["Normal"]))
    story.append(PageBreak())

    # Executive Summary
    story.append(Paragraph("Executive Summary", styles["Heading1"]))
    summary = """
    This report provides an AI-driven analysis of the uploaded financial dataset.
    It includes dataset profiling, technical indicators, machine learning predictions, market trend analysis, and investment recommendations."""
    story.append(Paragraph(summary, styles["BodyText"]))
    story.append(Spacer(1,20))
    Path("reports").mkdir(exist_ok = True)
    os.makedirs("reports", exist_ok = True)
    pdf_path = "reports/A-PQRP_Report.pdf"
    doc = SimpleDocTemplate(pdf_path)
    styles = getSampleStyleSheet()
    

    # Dataset Profile Table
    table_data = [["Metric", "Value"], ["Rows", len(df)],
                  ["Columns", len(df.columns)], ["Current Price", f"{df['Close'].iloc[-1]:.2f}"]]
    # Initialize session state variables
   
    table = Table(table_data)
    table.setStyle(TableStyle([
        ("BACKGROUND", (0,0), (-1,0), colors.darkblue),
        ("TEXTCOLOR", (0,0), (-1,0), colors.white),
        ("GRID", (0,0), (-1,-1), 1, colors.grey),
        ("BACKGROUND", (0,1), (-1,-1), colors.beige),
        ("BOTTOMPADDING", (0,0), (-1,0), 10),
    ]))
    story.append(table)
    story.append(Spacer(1,20))
    
    current_price = st.session_state["current_price"]
    expected_return = st.session_state["expected_return"]
    confidence = st.session_state["confidence"]
    Recommendation = st.session_state["recommendation"]
    future_predictions = st.session_state.get("future_predictions", [df["Close"].iloc[-1]] * 30)
    if future_predictions is None :
        st.error("Please run the ml Predictions page first")
        st.stop()
    # AI Recommendations
    story.append(Paragraph("AI Recommendation", styles["Heading1"]))
    story.append(Paragraph(f"<b>Recommendation :</b>{Recommendation}", styles["BodyText"]))
    story.append(Paragraph(f"<b>Expected Return :</b> {expected_return:.2f}%", styles["BodyText"]))
    story.append(Paragraph(f"<b>Confidence :</b> {confidence:.1f}%", styles["BodyText"]))

    # Prediciton Table
    prediction_table = [["Metric", "Value"],
                       ["Current Price", f"₹{current_price:.2f}"],
                       ["Tomorrow",f"{future_predictions[4]:.2f}"],
                       ["5-Day", f"₹{future_predictions[-1]:.2f}"],
                       ["30-Day",f"₹{future_predictions[-1]:.2f}"],
                       ["Confidence", f"{confidence:.1f}%"],
                       ["Expected Return", f"{expected_return:.2f}%"]]
    table = Table(prediction_table)
    table.setStyle(TableStyle([
        ("BACKGROUND", (0,0), (-1,0), colors.green),
        ("TEXTCOLOR", (0,0),(-1,0), colors.white),
        ("GRID", (0,0), (-1,-1), 1, colors.black),
    ]))
    story.append(table)
    
    # Footer
    story.append(Spacer(1,30))
    story.append((Paragraph("Generated by A-PQRP - AI Powered Quat Research Platform", styles["Italic"])))
    
    doc.build(story)
    return pdf_path

# UI
report_path = generate_report()
st.title("📄 Download Analysis Report")
if st.button("Generate PDF Report") :
    st.success("Report generated successfully!")
with open(report_path , "rb") as f :
    st.download_button("⬇️ Download PDF", 
                       data = f, 
                       file_name = "A-PQRP_Report.pdf",
                       mime = "application/pdf")    
